// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH69PumGNw__684deWOexPUL9tWa-4HOs',
    appId: '1:20239223931:web:02bf99a57d26f3e87ae6de',
    messagingSenderId: '20239223931',
    projectId: 'ai-sky-6827d',
    authDomain: 'ai-sky-6827d.firebaseapp.com',
    storageBucket: 'ai-sky-6827d.firebasestorage.app',
    measurementId: 'G-VW40QWHPLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHy6blkm5eHZYCUQRiPAWYZCScjGSDeCo',
    appId: '1:20239223931:android:071aed1a4f1f29eb7ae6de',
    messagingSenderId: '20239223931',
    projectId: 'ai-sky-6827d',
    storageBucket: 'ai-sky-6827d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4hk4kdhmh6lPzq_iXo0UDFRuUKzL04pc',
    appId: '1:20239223931:ios:db8a481583faec3b7ae6de',
    messagingSenderId: '20239223931',
    projectId: 'ai-sky-6827d',
    storageBucket: 'ai-sky-6827d.firebasestorage.app',
    iosBundleId: 'com.example.aiSky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4hk4kdhmh6lPzq_iXo0UDFRuUKzL04pc',
    appId: '1:20239223931:ios:db8a481583faec3b7ae6de',
    messagingSenderId: '20239223931',
    projectId: 'ai-sky-6827d',
    storageBucket: 'ai-sky-6827d.firebasestorage.app',
    iosBundleId: 'com.example.aiSky',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH69PumGNw__684deWOexPUL9tWa-4HOs',
    appId: '1:20239223931:web:ba0491aa97f04ce07ae6de',
    messagingSenderId: '20239223931',
    projectId: 'ai-sky-6827d',
    authDomain: 'ai-sky-6827d.firebaseapp.com',
    storageBucket: 'ai-sky-6827d.firebasestorage.app',
    measurementId: 'G-6WQGRQ79RF',
  );
}
